function P = ObtenerP(MRP_global, VA, SL)
    % Calcula la potencia articular P_GoA (Generada o Absorbida) en los 3 planos
    % P_GoA = M·e · [(ω_distal - ω_proximal)·e]
    %
    % CONVENCIÓN DE SIGNOS: Abs(-) / Gen(+)
    %   - Potencia POSITIVA: Músculo generando (concéntrico)
    %   - Potencia NEGATIVA: Músculo absorbiendo (excéntrico)
    %
    % ENTRADAS:
    %   MRP_global: Momentos reactivos en coord. GLOBALES (de ObtenerMRP) [N·m]
    %   VA: Velocidades angulares de cada segmento [deg/s] GLOBALES
    %   SL: Ejes anatómicos (System of Landmarks) GLOBALES
    %
    % SALIDA:
    %   P: Estructura con potencias [W] para cada articulación y plano
    
    % ⚠️ CONVERSIÓN CRÍTICA: deg/s → rad/s
    deg2rad_factor = pi / 180;
    
    % Convertir todas las velocidades angulares a rad/s
    VA_rad = struct();
    VA_rad.pelvis = VA.pelvis * deg2rad_factor;
    VA_rad.musloD = VA.musloD * deg2rad_factor;
    VA_rad.musloI = VA.musloI * deg2rad_factor;
    VA_rad.piernaD = VA.piernaD * deg2rad_factor;
    VA_rad.piernaI = VA.piernaI * deg2rad_factor;
    VA_rad.pieD = VA.pieD * deg2rad_factor;
    VA_rad.pieI = VA.pieI * deg2rad_factor;
    
    %% ========== CADERA DERECHA ==========
    
    % Flexión/Extensión (eje: k_pelvis)
    P.Cadera_D_FlexExt = calculo_pot(MRP_global.caderaD, ...
                                     VA_rad.musloD, ...
                                     VA_rad.pelvis, ...
                                     SL.k_pelv);
    
    % Abducción/Aducción (eje flotante: k_pelv × i_musloD)
    eje_flot_cad_D = normalizar(cross(SL.k_pelv, SL.i1, 2));
    P.Cadera_D_AbdAdd = calculo_pot(MRP_global.caderaD, ...
                                     VA_rad.musloD, ...
                                     VA_rad.pelvis, ...
                                     eje_flot_cad_D); 
    
    % Rotación (eje: i_musloD)
    P.Cadera_D_Rot = calculo_pot(MRP_global.caderaD, ...
                                 VA_rad.musloD, ...
                                 VA_rad.pelvis, ...
                                 SL.i1);
    
    %% ========== CADERA IZQUIERDA ==========
    
    P.Cadera_I_FlexExt = calculo_pot(MRP_global.caderaI, ...
                                     VA_rad.musloI, ...
                                     VA_rad.pelvis, ...
                                     SL.k_pelv);
    
    eje_flot_cad_I = normalizar(cross(SL.k_pelv, SL.i2, 2));
    P.Cadera_I_AbdAdd = calculo_pot(MRP_global.caderaI, ...
                                    VA_rad.musloI, ...
                                    VA_rad.pelvis, ...
                                    eje_flot_cad_I); 
    
    P.Cadera_I_Rot = calculo_pot(MRP_global.caderaI, ...
                                 VA_rad.musloI, ...
                                 VA_rad.pelvis, ...
                                 SL.i2); 
    
    %% ========== RODILLA DERECHA ==========
    
    P.Rodilla_D_FlexExt = calculo_pot(MRP_global.rodillaD, ...
                                       VA_rad.piernaD, ...
                                       VA_rad.musloD, ...
                                       SL.k1); 
    
    eje_flot_rod_D = normalizar(cross(SL.k1, SL.i3, 2));
    P.Rodilla_D_AbdAdd = calculo_pot(MRP_global.rodillaD, ...
                                     VA_rad.piernaD, ...
                                     VA_rad.musloD, ...
                                     eje_flot_rod_D);
    
    P.Rodilla_D_Rot = calculo_pot(MRP_global.rodillaD, ...
                                   VA_rad.piernaD, ...
                                   VA_rad.musloD, ...
                                   SL.i3); 
    
    %% ========== RODILLA IZQUIERDA ==========
    
    P.Rodilla_I_FlexExt = calculo_pot(MRP_global.rodillaI, ...
                                      VA_rad.piernaI, ...
                                      VA_rad.musloI, ...
                                      SL.k2); 
    
    eje_flot_rod_I = normalizar(cross(SL.k2, SL.i4, 2));
    P.Rodilla_I_AbdAdd = calculo_pot(MRP_global.rodillaI, ...
                                     VA_rad.piernaI, ...
                                     VA_rad.musloI, ...
                                     eje_flot_rod_I); 
    
    P.Rodilla_I_Rot = calculo_pot(MRP_global.rodillaI, ...
                                  VA_rad.piernaI, ...
                                  VA_rad.musloI, ...
                                  SL.i4); 
    
    %% ========== TOBILLO DERECHO ==========
    
    P.Tobillo_D_FlexExt = calculo_pot(MRP_global.tobilloD, ...
                                      VA_rad.pieD, ...
                                      VA_rad.piernaD, ...
                                      SL.k3);
    
    eje_flot_tob_D = normalizar(cross(SL.k3, SL.i5, 2));
    P.Tobillo_D_AbdAdd = calculo_pot(MRP_global.tobilloD, ...
                                     VA_rad.pieD, ...
                                     VA_rad.piernaD, ...
                                     eje_flot_tob_D);
    
    P.Tobillo_D_Rot = calculo_pot(MRP_global.tobilloD, ...
                                  VA_rad.pieD, ...
                                  VA_rad.piernaD, ...
                                  SL.i5);
    
    %% ========== TOBILLO IZQUIERDO ==========
    
    P.Tobillo_I_FlexExt = calculo_pot(MRP_global.tobilloI, ...
                                      VA_rad.pieI, ...
                                      VA_rad.piernaI, ...
                                      SL.k4);
    
    eje_flot_tob_I = normalizar(cross(SL.k4, SL.i6, 2));
    P.Tobillo_I_AbdAdd = calculo_pot(MRP_global.tobilloI, ...
                                     VA_rad.pieI, ...
                                     VA_rad.piernaI, ...
                                     eje_flot_tob_I); 
    
    P.Tobillo_I_Rot = calculo_pot(MRP_global.tobilloI, ...
                                  VA_rad.pieI, ...
                                  VA_rad.piernaI, ...
                                  SL.i6); 
    
    %% ========== FUNCIONES AUXILIARES ==========
    
    function p = calculo_pot(M_global, w_distal, w_proximal, eje)
        % Calcula P_GoA = M·e · [(ω_distal - ω_proximal)·e]
        %
        % M_global: momento reactivo GLOBAL [N×3] en [Nm]
        % w_distal: vel. angular segmento distal [N×3] en [rad/s] GLOBAL
        % w_proximal: vel. angular segmento proximal [N×3] en [rad/s] GLOBAL
        % eje: eje anatómico [N×3] GLOBAL normalizado
        
        % Proyectar el VECTOR momento sobre el eje anatómico
        M_e = sum(M_global .* eje, 2);  % [Nm] escalar
        
        % Velocidad angular relativa proyectada en el eje
        w_rel = w_distal - w_proximal;  % [rad/s] vectorial
        w_rel_e = sum(w_rel .* eje, 2);  % [rad/s] escalar
        
        % Potencia: P_GoA = M_e · ω_rel_e
        p = M_e .* w_rel_e;  % [W]
    end

    function e_norm = normalizar(v)
        % Normaliza vectores fila por fila evitando división por cero
        normas = vecnorm(v, 2, 2);
        normas(normas < 1e-10) = 1;
        e_norm = v ./ normas;
    end
end