function [CA, versor] = ObtenerCA(mar, ant, graficar)
    %% Pelvis
    versor.v_pelv = normalize((mar.p14-mar.p7), 2, 'norm');
    versor.w_pelv = normalize(cross((mar.p7-mar.p15), (mar.p14-mar.p15), 2), 2, 'norm');
    versor.u_pelv = cross(versor.v_pelv, versor.w_pelv, 2);

    CA.p_RHip = mar.p15 + 0.598 * ant.A2 * versor.u_pelv - 0.344 * ant.A2 * versor.v_pelv - 0.290 * ant.A2 * versor.w_pelv;
    CA.p_LHip = mar.p15 + 0.598 * ant.A2 * versor.u_pelv + 0.344 * ant.A2 * versor.v_pelv - 0.290 * ant.A2 * versor.w_pelv;
    
    %% Rodilla D
    versor.v_RCalf = normalize((mar.p3-mar.p5), 2, 'norm');
    versor.u_RCalf = normalize(cross((mar.p4-mar.p5), (mar.p3-mar.p5), 2), 2, 'norm');
    versor.w_RCalf = cross(versor.u_RCalf, versor.v_RCalf, 2);

    CA.p_RKnee = mar.p5 + 0.500 * ant.A11 * versor.w_RCalf;
    
    %% Rodilla I
    versor.v_LCalf = normalize((mar.p10-mar.p12), 2, 'norm');
    versor.u_LCalf = normalize(cross((mar.p10-mar.p12), (mar.p11-mar.p12), 2), 2, 'norm');
    versor.w_LCalf = cross(versor.u_LCalf, versor.v_LCalf, 2);

    CA.p_LKnee = mar.p12 - 0.500 * ant.A12 * versor.w_LCalf;
    
    %% Tobillo D
    versor.u_RFoot = normalize((mar.p1-mar.p2), 2, 'norm');
    versor.w_RFoot = normalize(cross((mar.p1-mar.p3), (mar.p2-mar.p3), 2), 2, 'norm');
    versor.v_RFoot = cross(versor.w_RFoot, versor.u_RFoot, 2);

    CA.p_RAnkle = mar.p3 + 0.016 * ant.A13 * versor.u_RFoot + 0.392 * ant.A15 * versor.v_RFoot + 0.478 * ant.A17 * versor.w_RFoot;
    CA.p_RToe = mar.p3 + 0.742 * ant.A13 * versor.u_RFoot + 1.074 * ant.A15 * versor.v_RFoot - 0.187 * ant.A19 * versor.w_RFoot;
    
    %% Tobillo I
    versor.u_LFoot = normalize((mar.p8-mar.p9), 2, 'norm');
    versor.w_LFoot = normalize(cross((mar.p8-mar.p10), (mar.p9-mar.p10), 2), 2, 'norm');
    versor.v_LFoot = cross(versor.w_LFoot, versor.u_LFoot, 2);

    CA.p_LAnkle = mar.p10 + 0.016 * ant.A14 * versor.u_LFoot + 0.392 * ant.A16 * versor.v_LFoot - 0.478 * ant.A18 * versor.w_LFoot;
    CA.p_LToe = mar.p10 + 0.742 * ant.A14 * versor.u_LFoot + 1.074 * ant.A16 * versor.v_LFoot + 0.187 * ant.A20 * versor.w_LFoot;
    
    
        %% GRAFICAR
    if graficar
        figure;
        
        % SUBPLOT 1: PELVIS
        subplot(2, 3, 1);
        origenes = mar.p15;
        vectores.u = versor.u_pelv;
        vectores.v = versor.v_pelv;
        vectores.w = versor.w_pelv;
        config = struct( ...
            'ColorU', [1 0 0], ...
            'ColorV', [0 1 0], ...
            'ColorW', [0 0 1], ...
            'EtiquetaO', 'Origen (sacrum)', ...
            'EtiquetaU', 'u\_pelvis', ...
            'EtiquetaV', 'v\_pelvis', ...
            'EtiquetaW', 'w\_pelvis', ...
            'Titulo', 'Vectores de la pelvis', ...
            'Frecuencia', 20, ...
            'MostrarOrigen', true);
        hold on;
        graficar_vectores(origenes, vectores, config);
        hold off;
        
        % SUBPLOT 2: PIERNA DERECHA
        subplot(2, 3, 2);
        origenes = mar.p5;
        vectores.u = versor.u_RCalf;
        vectores.v = versor.v_RCalf;
        vectores.w = versor.w_RCalf;
        config = struct( ...
            'ColorU', [1 0 0], ...
            'ColorV', [0 1 0], ...
            'ColorW', [0 0 1], ...
            'EtiquetaO', 'Origen (rodilla D)', ...
            'EtiquetaU', 'u\_RCalf', ...
            'EtiquetaV', 'v\_RCalf', ...
            'EtiquetaW', 'w\_RCalf', ...
            'Titulo', 'Vectores de la pierna derecha', ...
            'Frecuencia', 20, ...
            'MostrarOrigen', true);
        hold on;
        graficar_vectores(origenes, vectores, config);
        hold off;
        
        % SUBPLOT 3: PIERNA IZQUIERDA
        subplot(2, 3, 3);
        origenes = mar.p12;
        vectores.u = versor.u_LCalf;
        vectores.v = versor.v_LCalf;
        vectores.w = versor.w_LCalf;
        config = struct( ...
            'ColorU', [1 0 0], ...
            'ColorV', [0 1 0], ...
            'ColorW', [0 0 1], ...
            'EtiquetaO', 'Origen (rodilla I)', ...
            'EtiquetaU', 'u\_LCalf', ...
            'EtiquetaV', 'v\_LCalf', ...
            'EtiquetaW', 'w\_LCalf', ...
            'Titulo', 'Vectores de la pierna izquierda', ...
            'Frecuencia', 20, ...
            'MostrarOrigen', true);
        hold on;
        graficar_vectores(origenes, vectores, config);
        hold off;
        
        % SUBPLOT 4: PIE DERECHO
        subplot(2, 3, 5);
        origenes = mar.p3;
        vectores.u = versor.u_RFoot;
        vectores.v = versor.v_RFoot;
        vectores.w = versor.w_RFoot;
        config = struct( ...
            'ColorU', [1 0 0], ...
            'ColorV', [0 1 0], ...
            'ColorW', [0 0 1], ...
            'EtiquetaO', 'Origen (tobillo D)', ...
            'EtiquetaU', 'u\_RFoot', ...
            'EtiquetaV', 'v\_RFoot', ...
            'EtiquetaW', 'w\_RFoot', ...
            'Titulo', 'Vectores del pie derecho', ...
            'Frecuencia', 20, ...
            'MostrarOrigen', true);
        hold on;
        graficar_vectores(origenes, vectores, config);
        hold off;
        
        % SUBPLOT 5: PIE IZQUIERDO
        subplot(2, 3, 6);
        origenes = mar.p10;
        vectores.u = versor.u_LFoot;
        vectores.v = versor.v_LFoot;
        vectores.w = versor.w_LFoot;
        config = struct( ...
            'ColorU', [1 0 0], ...
            'ColorV', [0 1 0], ...
            'ColorW', [0 0 1], ...
            'EtiquetaO', 'Origen (tobillo I)', ...
            'EtiquetaU', 'u\_LFoot', ...
            'EtiquetaV', 'v\_LFoot', ...
            'EtiquetaW', 'w\_LFoot', ...
            'Titulo', 'Vectores del pie izquierdo', ...
            'Frecuencia', 20, ...
            'MostrarOrigen', true);
        hold on;
        graficar_vectores(origenes, vectores, config);
        hold off;
        
        sgtitle('Sistemas de coordenadas anatómicos');
    end
end